(UX): Add more meaningful error message for sqlite3
When the computer is missing sqlite3 or the path is not correctly
set, you get an error message like this:

  Error: apply: Cannot find executable “sqlite3”!

The motivation of this simple change is to see whether a simple
change to the error message might not change UX, and better
guide end-users who may not be familiar with dealing with
these terse error messages.